In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [5]:
data=pd.read_csv("/content/sample_data/DataStudents.csv")
df=pd.DataFrame(data)
df

    RollNo       Name  Age Maths  Science  English Total Average
0        1     Anish    18    25       35       56   116    NaN
1        2  Aasawari    20    33       78       34   145    48.3
2        3    Aditya    11    90       33       22   145    48.3
3        4   Apoorva    22    45       88       56   189      63
4        5      Anil    12    66       43       88   197    65.7
5        6     Bablu    13  NaN        35       53   110    NaN
6        7    Chetan    12    56       66       78  NaN     66.7
7        8   Chinmay    14    56       36       68   160    53.3
8        9    Chitra    15    67       22       32   121    40.3
9       10      Diya    16    54       78       88   220    73.3
10      11    Deepak    34    33       44       71   148    49.3
11      12     Dilip    18    87       89       37   213    NaN
12      13      Esha    19    89       53       40   182    60.7
13      14    Fatima    17    34       45       78   157    52.3
14      15      Faiz    11    32       51       27   110    36.7
15      16    Gaurav    19    80       30       28   138      46
16      17    Hitesh    20  NaN        74       30  NaN     64.7
17      18      Isha    14    50       90       56   196    65.3
18      19     Ishan    16    40       42       89   171      57
19      20       Jay    18    48       72       90   210      70

In [6]:
df.describe()

         RollNo        Age    Science    English
count  20.00000  20.000000  20.000000  20.000000
mean   10.50000  16.950000  55.200000  56.050000
std     5.91608   5.155222  22.018174  23.811707
min     1.00000  11.000000  22.000000  22.000000
25%     5.75000  13.750000  35.750000  33.500000
50%    10.50000  16.500000  48.000000  56.000000
75%    15.25000  19.000000  75.000000  78.000000
max    20.00000  34.000000  90.000000  90.000000

In [7]:
df.isnull().head(7)

   RollNo   Name    Age  Maths  Science  English  Total  Average
0   False  False  False  False    False    False  False    False
1   False  False  False  False    False    False  False    False
2   False  False  False  False    False    False  False    False
3   False  False  False  False    False    False  False    False
4   False  False  False  False    False    False  False    False
5   False  False  False  False    False    False  False    False
6   False  False  False  False    False    False  False    False

In [10]:
df.head(10)

   RollNo       Name  Age Maths  Science  English Total Average
0       1     Anish    18    25       35       56   116    NaN
1       2  Aasawari    20    33       78       34   145    48.3
2       3    Aditya    11    90       33       22   145    48.3
3       4   Apoorva    22    45       88       56   189      63
4       5      Anil    12    66       43       88   197    65.7
5       6     Bablu    13  NaN        35       53   110    NaN
6       7    Chetan    12    56       66       78  NaN     66.7
7       8   Chinmay    14    56       36       68   160    53.3
8       9    Chitra    15    67       22       32   121    40.3
9      10      Diya    16    54       78       88   220    73.3

In [14]:
df['Maths'] = df['Maths'].fillna(df['Maths'].mean())
df['Science'] = df['Science'].fillna(df['Science'].mean())
df['English'] = df['English'].fillna(df['English'].mean())
df['Total'] = df['Total'].fillna(df['Total'].mean())
df['Average'] = df['Average'].fillna(df['Average'].mean())
df.head(7)

TypeError: Could not convert 2533904566NaN 56566754338789343280NaN 504048 to numeric